# Generated by Django 2.2 on 2019-06-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.TextField(max_length=100)),
                ('NID', models.CharField(max_length=20)),
                ('Sign', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Applied')),
            ],
        ),
    ]
