# Generated by Django 2.2 on 2019-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bnaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='account_holder',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='applied',
            name='Sign',
        ),
        migrations.AddField(
            model_name='applied',
            name='Birth',
            field=models.CharField(default='s', max_length=20),
        ),
        migrations.AddField(
            model_name='applied',
            name='Branch',
            field=models.CharField(default='sd', max_length=20),
        ),
        migrations.AddField(
            model_name='applied',
            name='Mail',
            field=models.CharField(default='sd', max_length=250),
        ),
        migrations.AddField(
            model_name='applied',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applied',
            name='Phone',
            field=models.CharField(default='d', max_length=15),
        ),
    ]
