# Generated by Django 2.2 on 2019-07-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190708_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied',
            name='Birth',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applied',
            name='Branch',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applied',
            name='Mail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='applied',
            name='Phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
