# Generated by Django 2.2 on 2019-07-25 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190725_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='banker',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='deposite',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='Date',
        ),
        migrations.AddField(
            model_name='deposite',
            name='Deposite_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.Date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='Loan_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.Date'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='Transfer_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data.Date'),
        ),
    ]
