# Generated by Django 2.2 on 2019-07-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190725_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='Date',
            new_name='T_date',
        ),
    ]
