# Generated by Django 2.2 on 2019-07-25 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190725_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='Deposite_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
