# Generated by Django 2.2 on 2019-07-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20190726_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_request_name', models.CharField(max_length=100)),
                ('Loan_amount', models.IntegerField()),
            ],
        ),
    ]
