# Generated by Django 2.2 on 2019-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_loan_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='Deposite_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
