# Generated by Django 2.2 on 2019-07-27 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20190727_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='Transfer_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
